server:
  port: 8888

spring:
  application:
    name: admin-server
  # 代码国际化翻译支持
  messages:
    basename: i18n/messages #相对路径 开头请勿添加斜杠
    encoding: UTF-8

# tag::configuration-eureka[]
eureka:   #<1>
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8000}/eureka/
management:
  security:
    enabled: false
